version: '3'
services:
  mariadb:
    image: tiagouruba2016/mariadb:1.0
    container_name: "mariadb"
    ports:
      - 3306:3306
    volumes:
    - .db:/var/lib/mysql

    environment:
    - MARIADB_ROOT_PASSWORD=teste

  comentariosglobo:
    image: comentariosglobo
    container_name: "comentariosglobo"
    ports:
      - 5000:5000

    links:
    - mariadb

  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

  kuma:
    image: louislam/uptime-kuma:1
    container_name: "kuma"
    ports:
      - 3001:3001
    volumes:
      -  uptime-kuma:/app/data      
        
volumes:
  jenkins:
  uptime-kuma:    
  db:
