name: Build and deploy Python app to Azure Web App - comentariosglobo

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Mariadb install    
        uses: getong/mariadb-action@v1.1
        with:
          host port: 3306
          container port: 3306
          mariadb version: 'latest'
          mysql database: 'materiasglobo'
          mysql root password: ${{ secrets.RootPassword }} 
          mysql password: ${{ secrets.DatabasePassword }}
      
      #Mariadb install
      # - name: Setup MariaDB
      #   uses: docker://mariadb:latest
      #   with:
      #     env:
      #       MYSQL_ROOT_PASSWORD: ${{ secrets.DB_ROOT_PASSWORD }}
      #       MYSQL_DATABASE: 'testdb'
      #       MYSQL_USER: 'testuser'
      #       MYSQL_PASSWORD: ${{ secrets.DB_PASSWORD }

      - name: Set up Python version
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: |
          sudo apt-get install libmariadb-dev -y
          sudo apt-get install libmariadb3 -y
          pip install -r requirements.txt
        
      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v3
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A562B469B42C4BF093A0A3CC1BDA959B }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D2B45EA129B641B0896B613F21B6FDD9 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_66B4982F501A489E873154B467E23336 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'comentariosglobo'
          slot-name: 'Production'
          
